/*
 * This source file was generated by the Gradle 'init' task
 */
package psdk.EventEditor;

import org.junit.jupiter.api.Test;

class CoreTest {
    @Test void returnTrue() {
        assert(true);
    }
}
